### Get all reminders
GET http://localhost:8080/api/v1/reminders

### create reminder
POST http://localhost:8080/api/v1/reminders
Content-Type: application/json

{
  "title": "Buy Milk",
  "notes": "Buy Milk from Walmart",
  "category": "Home",
  "location": "Ottawa",
  "priority": "NONE",
  "dueDateTime": "2024-04-20 10:25"
}

### create reminder with title only
POST http://localhost:8080/api/v1/reminders
Content-Type: application/json

{
  "title": "Do not forget to pick up your keys"
}

### create reminder with title and past date
POST http://localhost:8080/api/v1/reminders
Content-Type: application/json

{
  "title": "Do not forget to pick up your keys",
  "dueDateTime": "2024-02-14 03:30"
}

### create reminder without title
POST http://localhost:8080/api/v1/reminders
Content-Type: application/json

{
  "note": "Just a note"
}

### update reminder, PUT request
PUT http://localhost:8080/api/v1/reminders/4
Content-Type: application/json

{
  "title": "Buy Extra Fat Milk",
  "notes": "Buy Extra Fat Milk"
}

### update some parts of reminder
PATCH http://localhost:8080/api/v1/reminders/4
Content-Type: application/json

{
  "title": "Buy Extra Fat Milk",
  "notes": "Buy Extra Fat Milk from Walmart"
}

### get existing reminder by id
GET http://localhost:8080/api/v1/reminders/2

### get non-existing reminder by id
GET http://localhost:8080/api/v1/reminders/12345678

### delete reminder by id
DELETE http://localhost:8080/api/v1/reminders/2

### unsupported method call
DELETE http://localhost:8080/api/v1/reminder
