reminder:
  default-category-name: reminder
spring:
  application:
    name: reminders
  datasource:
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:mem:remindersdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

